import { ChevronRight } from 'lucide-react'
import { useState } from 'react'
import { agentVisual, useWorkspace } from '../platform/react'
import type { ActivityEvent } from '../platform/types'
import { durationLabel, timeOf } from '../utils/format'
import { colorClasses } from './colorClasses'

/**
 * One line of the audit trail.
 *
 * A 3px left rule in the sending agent's colour means "this agent spoke".
 * The header is monospaced because everything in it — a timestamp, an agent
 * id, an A2A task type — was generated by a machine. The payload disclosure
 * is what you open when someone asks how the agents actually talk to each
 * other, instead of switching to a slide.
 */
export default function TranscriptEntry({ event }: { event: ActivityEvent }) {
  const { workspace } = useWorkspace()
  const [showPayload, setShowPayload] = useState(false)

  const from = agentVisual(workspace, event.fromAgent)
  const to = event.toAgent ? agentVisual(workspace, event.toAgent) : undefined
  const color = colorClasses[from.color]

  return (
    <li className="transcript-entry relative flex gap-3 pb-5 last:pb-0">
      <span className={`absolute left-0 top-1 h-[calc(100%-0.5rem)] w-[3px] rounded-full ${color.rule}`} />

      <div className="min-w-0 flex-1 pl-4">
        <p className="flex flex-wrap items-center gap-x-2 gap-y-1 font-mono text-[11px] text-gray-400">
          <span>{timeOf(event.timestamp)}</span>
          <span className="text-gray-600">
            {from.name}
            {to && <span className="text-gray-400"> → {to.name}</span>}
          </span>
          {event.taskType && (
            <span className={`font-medium ${color.text}`}>{event.taskType}</span>
          )}
          {event.durationMs !== undefined && (
            <span className="text-gray-400">{durationLabel(event.durationMs)}</span>
          )}
        </p>

        <p
          className={`mt-1 text-sm font-medium ${
            event.level === 'warn'
              ? 'text-amber-700'
              : event.level === 'error'
                ? 'text-red-600'
                : 'text-gray-900'
          }`}
        >
          {event.title}
        </p>

        {event.body?.map((line) => (
          <p key={line} className="mt-1 max-w-[68ch] text-sm leading-relaxed text-gray-600">
            {line}
          </p>
        ))}

        {event.logs && event.logs.length > 0 && (
          <ul className="mt-2 space-y-0.5">
            {event.logs.map((line) => (
              <li key={line} className="pl-3 text-xs text-gray-400">
                <span className="mr-1.5 text-gray-300">›</span>
                {line}
              </li>
            ))}
          </ul>
        )}

        {event.payload !== undefined && (
          <div className="mt-2">
            <button
              type="button"
              onClick={() => setShowPayload((open) => !open)}
              aria-expanded={showPayload}
              className="flex items-center gap-1 rounded text-xs text-gray-400 hover:text-gray-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-400"
            >
              <ChevronRight
                className={`h-3 w-3 transition-transform ${showPayload ? 'rotate-90' : ''}`}
              />
              {showPayload ? 'hide payload' : 'show payload'}
            </button>

            {showPayload && (
              <pre className="mt-2 max-w-full overflow-x-auto rounded-lg bg-gray-900 p-3 font-mono text-[11px] leading-relaxed text-gray-100">
                {JSON.stringify(event.payload, null, 2)}
              </pre>
            )}
          </div>
        )}
      </div>
    </li>
  )
}
