import type { BackgroundTicket } from '../scenarios/types'

/**
 * Tickets that exist only so the board is not empty. They have no scripted
 * run behind them — opening one shows the ticket with an empty transcript and
 * a "start investigation" call to action, which is exactly what a real
 * untouched ticket looks like.
 */
export const BACKGROUND_TICKETS: BackgroundTicket[] = [
  {
    workspaceId: 'procol',
    reference: 'PRO-1242',
    title: 'PO approval webhook failing',
    customer: 'Detected by monitoring',
    status: 'INVESTIGATING',
    priority: 'CRITICAL',
    channel: 'signal',
    category: 'Integrations',
    progress: 45,
    currentAgentId: 'dev-agent',
    currentAgentAction: 'Analysing the delivery log',
    updatedMinutesAgo: 8,
  },
  {
    workspaceId: 'procol',
    reference: 'PRO-1231',
    title: 'Report download times out for large tenants',
    customer: 'Meridian Industries',
    status: 'INVESTIGATING',
    priority: 'MEDIUM',
    channel: 'email',
    category: 'Reporting',
    progress: 60,
    currentAgentId: 'clara',
    currentAgentAction: 'Fetching tenant context',
    updatedMinutesAgo: 18,
  },
  {
    workspaceId: 'procol',
    reference: 'PRO-1189',
    title: 'GST not applied for ABC Corp',
    customer: 'ABC Corp',
    status: 'RESOLVED',
    priority: 'HIGH',
    channel: 'email',
    category: 'Billing & invoicing',
    progress: 100,
    currentAgentAction: 'Closed',
    updatedMinutesAgo: 60 * 24 * 21,
  },
  {
    workspaceId: 'procol',
    reference: 'PRO-1251',
    title: 'How do I extend an auction deadline?',
    customer: 'Kanti Metals',
    status: 'NEW',
    priority: 'LOW',
    channel: 'portal',
    category: 'How-to',
    progress: 0,
    updatedMinutesAgo: 3,
  },
  {
    workspaceId: 'acmecloud',
    reference: 'ACME-7804',
    title: 'Webhook retries exhausted for tenant northwind',
    customer: 'Northwind Ltd',
    status: 'INVESTIGATING',
    priority: 'HIGH',
    channel: 'signal',
    category: 'Integrations',
    progress: 35,
    currentAgentId: 'dev-agent',
    currentAgentAction: 'Reading the delivery log',
    updatedMinutesAgo: 22,
  },
  {
    workspaceId: 'acmecloud',
    reference: 'ACME-7790',
    title: 'SSO metadata refresh fails on renewal',
    customer: 'Vertex Health',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    channel: 'email',
    category: 'Authentication',
    progress: 100,
    currentAgentAction: 'Closed',
    updatedMinutesAgo: 60 * 24 * 9,
  },
  {
    workspaceId: 'acmecloud',
    reference: 'ACME-7833',
    title: 'Export CSV missing the last column',
    customer: 'XYZ Corp',
    status: 'NEW',
    priority: 'LOW',
    channel: 'portal',
    category: 'Reporting',
    progress: 0,
    updatedMinutesAgo: 2,
  },
]
