import type { Scenario } from './types'

/**
 * TEST CASE 1 — Procol · the full loop closes.
 *
 * A customer sentence becomes a root cause, a pull request, a passing test
 * suite, a human decision and a customer email — on one audited timeline.
 * Every agent in the workspace is exercised, which is why this is the run to
 * rehearse until it is boring.
 */
export const procolGstScenario: Scenario = {
  id: 'procol-gst',
  workspaceId: 'procol',
  path: 'CODE_FIX',
  status: 'AWAITING_APPROVAL',
  approvalPolicyId: 'code-billing',
  replayScale: 420,

  ticket: {
    reference: 'PRO-1245',
    title: 'Invoice GST calculation incorrect',
    description:
      'March invoices are showing GST of 12% instead of 18% for ABC Corp. The discount is correct; the tax is not.',
    customer: 'ABC Corp',
    reportedBy: 'John Doe · Finance',
    channel: 'chat',
    priority: 'HIGH',
    category: 'Billing & invoicing',
    impact: 'Every purchase order raised this month',
    createdMinutesAgo: 14,
    attachment: 'invoice_sample.pdf',
    issueQuote: [
      'Our March invoices are showing GST of 12% instead of 18%.',
      'The discount looks right but the tax is wrong on every PO raised this month. This is holding up our payment run.',
    ],
  },

  events: [
    {
      atSeconds: 0,
      from: 'brain',
      kind: 'thought',
      title: 'Ticket received from the customer chat',
      body: [
        'Classified as a billing defect, high priority. I do not have this tenant’s tax configuration, so I need product context before anyone touches code.',
      ],
      level: 'info',
      durationMs: 640,
    },
    {
      atSeconds: 2,
      from: 'brain',
      kind: 'thought',
      title: 'Looking for an agent that can answer product questions',
      body: [
        'I am not calling Clara because I know Clara exists. I am asking the registry who declares product_knowledge — in this workspace, that is Clara.',
      ],
      level: 'info',
      durationMs: 180,
    },
    {
      atSeconds: 3,
      from: 'brain',
      to: 'clara',
      taskType: 'GET_PRODUCT_CONTEXT',
      kind: 'request',
      title: 'What is the expected GST configuration for ABC Corp?',
      payload: {
        taskId: 'TASK-8f21',
        from: 'brain',
        to: 'clara',
        type: 'GET_PRODUCT_CONTEXT',
        context: { ticketId: 'PRO-1245', customer: 'ABC Corp', issue: 'Invoice GST calculation incorrect' },
      },
      level: 'info',
    },
    {
      atSeconds: 4,
      from: 'clara',
      to: 'brain',
      taskType: 'GET_PRODUCT_CONTEXT',
      kind: 'response',
      title: 'Expected GST 18%, discount 10%, formula base − discount + gst',
      body: [
        'The tenant is configured correctly for intra-state GST at 18%. The billed rate does not match the configured rate, so this is a product defect rather than a tenant misconfiguration.',
      ],
      logs: [
        'matched 2 knowledge documents',
        'read billing-config.md#gst',
        'read abc-corp tenant settings v1.4',
      ],
      durationMs: 820,
      level: 'success',
      completesStage: 'context',
      payload: {
        taskId: 'TASK-8f21',
        status: 'completed',
        agent: 'clara',
        result: {
          customer: 'ABC Corp',
          expectedGst: 18,
          discount: 10,
          formula: 'base - discount + gst',
          isProductDefect: true,
          citations: ['billing-config.md#gst'],
        },
      },
    },
    {
      atSeconds: 6,
      from: 'brain',
      kind: 'thought',
      title: 'Decision: this is a code fix, not a configuration change',
      body: [
        'The tenant is configured correctly and the defect is in product behaviour, so I am routing to engineering. If the configuration had been wrong I would have stopped here and drafted a remediation instead.',
      ],
      level: 'info',
      durationMs: 910,
    },
    {
      atSeconds: 8,
      from: 'brain',
      to: 'dev-agent',
      taskType: 'INVESTIGATE_BUG',
      kind: 'request',
      title: 'Trace the GST defect and open a pull request',
      payload: {
        taskId: 'TASK-c104',
        from: 'brain',
        to: 'dev-agent',
        type: 'INVESTIGATE_BUG',
        context: {
          ticketId: 'PRO-1245',
          issue: 'Invoice GST calculation incorrect',
          productContext: { expectedGst: 18, discount: 10, formula: 'base - discount + gst' },
        },
      },
      level: 'info',
    },
    {
      atSeconds: 11,
      from: 'dev-agent',
      to: 'brain',
      taskType: 'INVESTIGATE_BUG',
      kind: 'response',
      title: 'Root cause: tenant context never reaches the GST calculator',
      body: [
        'calculateInvoice() reads the module-level DEFAULT_GST_RATE constant instead of the tenant’s configured rate, so every tenant is billed at the 12% default regardless of their settings.',
      ],
      logs: [
        'indexed 3 files in src/billing',
        'located calculateInvoice() in invoiceCalculator.js:7',
        'confirmed customerConfig.js holds gstPercent: 18 for ABC Corp',
        'opened PR #452 against main',
      ],
      durationMs: 4180,
      level: 'success',
      completesStage: 'investigate',
      payload: {
        taskId: 'TASK-c104',
        status: 'completed',
        agent: 'dev-agent',
        result: { confidence: 0.94, filesChanged: ['src/invoiceCalculator.js'] },
        artifacts: [{ kind: 'ROOT_CAUSE' }, { kind: 'PR', title: 'PR #452' }],
      },
    },
    {
      atSeconds: 12,
      from: 'dev-agent',
      kind: 'artifact',
      artifactId: 'root-cause',
      title: 'Root cause recorded',
      level: 'success',
    },
    {
      atSeconds: 13,
      from: 'dev-agent',
      kind: 'artifact',
      artifactId: 'pr-452',
      title: 'Pull request #452 opened',
      level: 'success',
    },
    {
      atSeconds: 15,
      from: 'brain',
      to: 'qa-agent',
      taskType: 'VALIDATE_FIX',
      kind: 'request',
      title: 'Validate PR #452 against the invoice regression suite',
      payload: {
        taskId: 'TASK-d77a',
        from: 'brain',
        to: 'qa-agent',
        type: 'VALIDATE_FIX',
        context: { ticketId: 'PRO-1245', branch: 'fix/gst-tenant-rate', pr: 452 },
      },
      level: 'info',
    },
    {
      atSeconds: 18,
      from: 'qa-agent',
      to: 'brain',
      taskType: 'VALIDATE_FIX',
      kind: 'response',
      title: '47 of 47 tests passed',
      body: ['The invoice, tax and discount suites all pass against the patched branch.'],
      logs: [
        'checked out fix/gst-tenant-rate',
        'ran 47 assertions across 3 suites',
        'no regressions in discount or rounding',
      ],
      durationMs: 1830,
      level: 'success',
      completesStage: 'verify',
      payload: {
        taskId: 'TASK-d77a',
        status: 'completed',
        agent: 'qa-agent',
        result: { status: 'passed', total: 47, passed: 47, failed: 0, durationMs: 1830 },
      },
    },
    {
      atSeconds: 19,
      from: 'qa-agent',
      kind: 'artifact',
      artifactId: 'tests-invoice',
      title: 'Test report recorded',
      level: 'success',
    },
    {
      atSeconds: 21,
      from: 'lens',
      to: 'brain',
      taskType: 'IMPACT_ANALYSIS',
      kind: 'response',
      title: '14 tenants and 312 invoices carry the same defect',
      body: [
        'Every tenant whose configured GST rate differs from the default has been billed at 12% since 2 March. A support tool would have closed this ticket; the other thirteen customers would have found out on their own.',
      ],
      logs: [
        'compiled canonical query against procurement-db',
        'scanned invoices since 2026-03-02',
        'grouped by tenant — 14 affected',
      ],
      durationMs: 760,
      level: 'warn',
    },
    {
      atSeconds: 22,
      from: 'lens',
      kind: 'artifact',
      artifactId: 'impact-gst',
      title: 'Blast radius recorded',
      level: 'warn',
    },
    {
      atSeconds: 24,
      from: 'brain',
      kind: 'gate',
      title: 'Stopping for human approval',
      body: [
        'Code changes to billing always require human approval. I have a root cause, a pull request, a passing suite and a blast radius — the decision is yours.',
      ],
      level: 'warn',
    },
  ],

  artifacts: [
    {
      id: 'root-cause',
      kind: 'ROOT_CAUSE',
      title: 'Root cause',
      createdBy: 'dev-agent',
      data: {
        headline: 'Tenant context is never passed into the GST calculator.',
        detail:
          'calculateInvoice() applies the module-level DEFAULT_GST_RATE constant instead of the tenant’s configured gstPercent, so every tenant falls back to the default 12% slab regardless of their settings.',
        evidence: [
          'src/invoiceCalculator.js:7 — const gst = taxable * (DEFAULT_GST_RATE / 100)',
          'src/customerConfig.js — ABC Corp: { gstPercent: 18, discountPercent: 10 }',
          'tenantConfig is accepted as a parameter but only read for the discount',
        ],
      },
    },
    {
      id: 'pr-452',
      kind: 'PR',
      title: 'PR #452',
      createdBy: 'dev-agent',
      data: {
        number: '#452',
        title: 'Use the tenant’s configured GST rate in calculateInvoice',
        url: 'https://github.com/procol-hack/demo-repo/pull/452',
        repository: 'procol-hack/demo-repo',
        filesChanged: ['src/invoiceCalculator.js'],
        additions: 7,
        deletions: 3,
        state: 'open',
        diff: [
          { type: 'context', text: '  const taxable = base - discount;' },
          { type: 'remove', text: '  const gst = taxable * (DEFAULT_GST_RATE / 100);' },
          { type: 'add', text: '  const rate = tenantConfig?.gstPercent ?? DEFAULT_GST_RATE;' },
          { type: 'add', text: '  const gst = taxable * (rate / 100);' },
          { type: 'context', text: '  return { base, discount, taxable, gst, total: taxable + gst };' },
        ],
      },
    },
    {
      id: 'tests-invoice',
      kind: 'TEST_RESULT',
      title: 'Invoice regression suite',
      createdBy: 'qa-agent',
      data: {
        suite: 'Invoice & billing',
        total: 47,
        passed: 47,
        failed: 0,
        durationMs: 1830,
        cases: [
          'GST applied at the tenant’s configured rate',
          'Discount applied before tax',
          'Default rate used when the tenant has no override',
          'Multi-currency rounding unchanged',
          'Credit notes unchanged',
        ],
      },
    },
    {
      id: 'impact-gst',
      kind: 'IMPACT',
      title: 'Blast radius',
      createdBy: 'lens',
      data: {
        affectedTenants: 14,
        affectedRecords: 312,
        recordLabel: 'invoices',
        firstSeen: '2 March',
        trend: [
          { date: '2 Mar', count: 18 },
          { date: '9 Mar', count: 46 },
          { date: '16 Mar', count: 83 },
          { date: '23 Mar', count: 71 },
          { date: '30 Mar', count: 94 },
        ],
      },
    },
    {
      id: 'reply-gst',
      kind: 'CUSTOMER_REPLY',
      title: 'Customer reply',
      createdBy: 'brain',
      data: {
        subject: 'Invoice GST issue resolved — PRO-1245',
        body: [
          'Hi ABC Corp,',
          'We have identified and fixed the issue causing GST to be billed at 12% instead of your configured 18% on March invoices. The calculation was falling back to a default rate instead of reading your tenant configuration.',
          'The fix has passed our full invoice regression suite and has been approved for release. Your affected March invoices are being re-issued — you do not need to raise them again.',
          'If anything still looks wrong on your next invoice, reply to this ticket and it will come straight back to us.',
        ],
        signature: 'Procol Support',
        sent: false,
      },
    },
  ],

  memory: {
    title: 'Tenant tax configuration not read by the invoice calculator',
    symptom: 'Invoice tax billed at the platform default instead of the tenant’s configured rate',
    rootCause:
      'calculateInvoice() used the module-level DEFAULT_GST_RATE constant instead of tenantConfig.gstPercent.',
    resolution:
      'Read the rate from the tenant configuration and fall back to the default only when it is absent. PR #452.',
    path: 'CODE_FIX',
    tags: ['gst', 'tax', 'invoice', 'billing', 'tenant-config', 'calculation', 'rate'],
    reuseCount: 0,
    minutesSavedPerReuse: 190,
    relatedKnowledgeIds: ['gst-configuration', 'invoice-process'],
  },
}
